services:
  api:
    build:
      context: ./api
    container_name: yt-api
    restart: unless-stopped
    networks:
      - yt-net

  proxy:
    build:
      context: .
    container_name: yt-proxy
    depends_on:
      - api
    ports:
      - "8080:80"
    restart: unless-stopped
    networks:
      - yt-net

networks:
  yt-net:
    driver: bridge
