[project]
name = "api"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "fastapi>=0.116.2",
    "uvicorn[standard]>=0.35.0",
    "yt-dlp>=2025.9.5",
]
